const CASE_STUDIES = [
  {
    id: 'CS01',
    title: 'SEARCH REDESIGN',
    desc: 'Reimagining property search for 200M+ users. Zero-to-one systems thinking at scale.',
    tags: 'UX // SYSTEMS // RESEARCH',
    color: '#00F7FF',
    cityX: 0.22, cityY: 0.32,
    href: 'case-studies/search-redesign.html',
  },
  {
    id: 'CS02',
    title: 'DESIGN SYSTEM',
    desc: 'Building a unified component language across 12 product teams and 3 platforms.',
    tags: 'SYSTEMS // COMPONENTS // SCALE',
    color: '#FF00AA',
    cityX: 0.38, cityY: 0.62,
    href: 'case-studies/design-system.html',
  },
  {
    id: 'CS03',
    title: 'DATA EXPERIENCE',
    desc: 'Translating complex market data into intuitive, actionable homebuyer intelligence.',
    tags: 'DATA VIZ // UX // STRATEGY',
    color: '#7A00FF',
    cityX: 0.60, cityY: 0.28,
    href: 'case-studies/data-experience.html',
  },
  {
    id: 'CS04',
    title: 'MOBILE FLOWS',
    desc: 'End-to-end mobile journey redesign increasing engagement by 34%.',
    tags: 'MOBILE // FLOWS // TESTING',
    color: '#FF6B35',
    cityX: 0.74, cityY: 0.58,
    href: 'case-studies/mobile-flows.html',
  },
  {
    id: 'CS05',
    title: 'AI ASSISTANT',
    desc: 'Designing human-centered AI interactions for real estate guidance.',
    tags: 'AI // CONVERSATION // ETHICS',
    color: '#00FF88',
    cityX: 0.50, cityY: 0.72,
    href: 'case-studies/ai-assistant.html',
  },
];
